# Copyright © 2021 - 2023 SUSE LLC
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


name: Rancher Desktop - Epinio CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

# env:
#   KUBECONFIG: ${{ github.workspace }}/kubeconfig-epinio-ci

jobs:
#   rancher-desktop-epinio-macos:
#     runs-on: macos-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Install Dependencies
#         run: |
#           brew install kubernetes-cli helm coreutils

#       - name: Installation rancher-desktop-epinio-macos
#         # env:
#           # # REGEX: Scenario4
#           # REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#           # REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
#           # AWS_ZONE_ID: ${{ secrets.AWS_ZONE_ID }}
#           # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           # # Use a random host name, so we don't collide with our workflows on EKS
#           # AWS_DOMAIN: id${{ steps.create-cluster.outputs.ID }}-${{ secrets.AWS_DOMAIN }}
#           # EPINIO_SYSTEM_DOMAIN: id${{ steps.create-cluster.outputs.ID }}-${{ secrets.AWS_DOMAIN }}
#           # EPINIO_TIMEOUT_MULTIPLIER: 3
#           # INGRESS_CONTROLLER: nginx
#           # # EXTRAENV_NAME: SESSION_KEY
#           # # EXTRAENV_VALUE: 12345
#         run: |
#           # echo "System Domain: $AWS_DOMAIN"
#           # export KUBECONFIG=${{ env.KUBECONFIG }}
#           export PATH=$HOME/.rd/bin:$PATH
#           export PATH=$PATH:$HOME/Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/bin/
#           ./full_rancherddesktop_epinio.sh


  rancher-desktop-epinio-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          brew install kubernetes-cli helm coreutils go@1.20

      - name: Installation of Rancher Desktop on MacOS
        run: |
          export PATH=$HOME/.rd/bin:$PATH
          export PATH=$PATH:$HOME/Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/bin/
          ./rd_install_mac.sh

      - name: Installation of Epinio and push an App
        run: |
          ./ep_install_on_rd.sh

      - name: Uninstall of Epinio
        run: |
          ./ep_uninstall_on_rd.sh

      - name: Uninstall of Rancher Desktop
        run: |
          export PATH=$HOME/.rd/bin:$PATH
          export PATH=$PATH:$HOME/Applications/Rancher\ Desktop.app/Contents/Resources/resources/darwin/bin/
          ./rd_uninstall.sh
